# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gameVerkauf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gameVerkauf
  pod 'Firebase/Core'  
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'TextFieldEffects'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'JSQMessagesViewController'
  pod 'SDWebImage'
  pod ‘SkyFloatingLabelTextField’
  pod 'LiquidFloatingActionButton', :git => 'https://github.com/alexsanderkhitev/LiquidFloatingActionButton.git'
  pod "SwiftPhotoGallery"
  pod 'Fusuma'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

  target 'gameVerkaufTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
